src/unit12/pets/config/routes.rb
Petadoption::Application.routes.draw do
  get "user_sessions/new"
  get "users/new"
  get "users/edit"
  get "animals/index"

  resources :foster_parents
  resources :considerations
  resources :considered_items
  resources :line_items
  resources :adoptions
  resources :pets
  resources :users
  resources :user_sessions

  resources :foster_parents do
    get :who_fostered
  end

  root to: 'animals#index', as: 'animals'

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

end

src/unit12/pets/app/models/pet.rb
class Pet < ActiveRecord::Base
	STATUSES = [ "Avaliable", "Fostered" ]

	#a pet can have many considerations and many lineitems
	has_many :line_items
	has_many :considered_items

	#ensure that a pet isn't being considerd and that it doesn't have any lineitems before it is deleted
	before_destroy :ensure_not_referenced_by_any_line_item
	before_destroy :ensure_not_referenced_by_any_considered_item

	#validation code for a pet, must have the given fields and successfully pass other validations
	validates :name, :age, :pet_type, :description, :image_url, presence: true
	validates :age, numericality: {greater_than_or_equal_to: 0}
	validates :image_url, allow_blank: true, format: { 
		with: %r{\.(gif|jpg|png)\z}i,
		message: 'must be a URL for GIF, JPG or PNG image.'
	}
	validates :status, inclusion: STATUSES

	private

    	# ensure that there are no line items referencing this product
		def ensure_not_referenced_by_any_line_item 
			if line_items.empty?
				return true 
			else
				errors.add(:base, 'Line Items present')
				return false 
			end
		end

		# ensure that there are no considered items referencing this product
		def ensure_not_referenced_by_any_considered_item 
			if considered_items.empty?
				return true 
			else
				errors.add(:base, 'Consideraion Items present')
				return false 
			end
		end
end

src/unit12/pets/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :check_rights, only: [:new, :create, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.order(sort_column + " " + sort_direction)
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pets_url, notice: 'Pet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pet }
      else
        format.html { render action: 'new' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pets_url, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :pet_type, :age, :description, :image_url, :status)
    end

    #following two methods used for sorting
    def sort_column
      Pet.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def check_rights
      if !current_user || !current_user.is_admin
        respond_to do |format|
          format.html { redirect_to pets_url, notice: 'Only administrators can add, remove, or edit pets.'  }
          format.json
        end
      end
    end
end

src/unit12/pets/app/helpers/pets_helper.rb
module PetsHelper
end

src/unit12/pets/app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pet_type %><br>
    <%= f.text_field :pet_type %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, Pet::STATUSES, prompt: "Select pet's status" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/unit12/pets/app/views/pets/edit.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

src/unit12/pets/app/views/pets/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>Pets Listing</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th><%= sortable "name" %></th>
      <th><%= sortable "pet_type", "Pet Type" %></th>
      <th><%= sortable "age" %></th>
      <th><%= sortable "description" %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= image_tag(pet.image_url, class: 'list_image') %> 
        </td>
        
        <td class="list_description">
        	<%=pet.name %>
        </td>
        
        <td class="list_description">
        	<%=pet.pet_type %>
        </td>
        
        <td class="list_description">
        	<%=pet.age %>
        </td>
        
        <td class="list_description">
        	<%= truncate(strip_tags(pet.description), length: 80) %>
        </td>
        <% if current_user && current_user.is_admin %>
        <td class="list_actions">
          <%= link_to 'Show', pet %><br/>
          <%= link_to 'Edit', edit_pet_path(pet) %>
          <br/> 
          <%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
		<% else %>
			<td></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && current_user.is_admin %>
	<%= link_to 'New Pet', new_pet_path %>
<% end %>

src/unit12/pets/app/views/pets/new.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

src/unit12/pets/app/views/pets/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Pet type:</strong>
  <%= @pet.pet_type %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @pet.image_url %>
</p>

<p>
  <strong>Status:</strong>
  <%= @pet.status %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>