src/unit12/pets/config/routes.rb
Petadoption::Application.routes.draw do
  get "user_sessions/new"
  get "users/new"
  get "users/edit"
  get "animals/index"

  resources :foster_parents
  resources :considerations
  resources :considered_items
  resources :line_items
  resources :adoptions
  resources :pets
  resources :users
  resources :user_sessions

  resources :foster_parents do
    get :who_fostered
  end

  root to: 'animals#index', as: 'animals'

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'

end

src/unit12/pets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pet Adoption</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body class='<%= controller.controller_name %>'>

<div id="banner">
	<%= image_tag("logo.png") %>
	<%= @page_title || "Pet Adoption" %>
</div>

<div id="columns">
	<div id="side"> 
		<div id="user_nav"> 
			<% if current_user %>
				<ul>
					<li><b>Welcome, <%= current_user.username %></b></li>
					<li><%= link_to "Edit Profile", edit_user_path(:current) %></li>
		 			<li><%= link_to "Logout", logout_path %></li>
		 		</ul>
			<% else %>
				<ul>
					<li><%= link_to "Register", new_user_path %></li>
				 	<li><%= link_to "Log in", login_path %></li>
				 </ul>
			<% end %> 	
		</div> 

		<ul>
			<li><b>Navigation</b></li>
			<li><%= link_to 'Home', animals_path %></li>
			<li><%= link_to 'Pets', pets_path %></li> 
		</ul>

		<div id="consideration">
			<% if @consideration %>
				<%= hidden_div_if(@consideration.considered_items.empty?, id: 'consideration') do %> 
					<%= render @consideration %>
				<% end %>
			<% end %>
		</div>
	</div>
	<div id="main"> 
		<%= yield %>
	</div>
</div>

</body>

</html>