src/unit15/barter/config/routes.rb
Barter::Application.routes.draw do
  resources :line_items

  resources :offers

  get "user_sessions/new"
  get "users/new"
  get "users/edit"
  resources :items
  resources :users 
  resources :user_sessions

  root 'items#index'

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  get 'register' => 'users#new'

  get 'offers/:id/accept' => 'offers#accept', :as => :accept
  get 'offers/:id/decline' => 'offers#decline', :as => :decline

end

src/unit15/barter/app/models/item.rb
class Item < ActiveRecord::Base
	STATUSES = ["Avaliable", "Taken"]

	belongs_to :user
	mount_uploader :image, ImageUploader

	has_many :line_items
	has_many :offers
	before_destroy :ensure_not_referenced_by_any_line_item
	before_destroy :ensure_not_referenced_by_any_offer

	validates :status, inclusion: STATUSES
	validates :title, presence: true

  scope :mine, -> { where user_id: UserSession.current_user.id }
  scope :avaliable, -> { where status: "Avaliable" }
  scope :taken, -> { where status: "Taken" }

  def belongs_to_me?
		user.id == UserSession.current_user.id
	end

	private
		def ensure_not_referenced_by_any_line_item
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
			end
		end

		def ensure_not_referenced_by_any_offer
			if offers.empty?
				return true
			else
				errors.add(:base, 'Offer present')
				return false
			end
		end
end

src/unit15/barter/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :check_rights, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if not params[:type]
      @items = Item.avaliable
      @type = "Avaliable"
    else
      if params[:type] == "traded" 
        @items = Item.taken
        @type = "Traded"
      else
        @items = Item.mine
        @type = "My"
      end
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :image).merge(user_id: current_user.id).merge(status: "Avaliable")
    end
end

src/unit15/barter/app/helpers/items_helper.rb
module ItemsHelper
end

src/unit15/barter/app/views/items/_form.html.erb
<%= form_for @item, :html => {:multipart => true} do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <!--<% if @item and @item.status = "Taken" %>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.select :status, ["Taken", "Avaliable"] %>
    </div>
  <% end %>-->
  <div>
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/unit15/barter/app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

src/unit15/barter/app/views/items/index.html.erb
<h1><%= @type %> items</h1>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th>Title</th>
      <th>Description</th> 
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= image_tag item.image.to_s %></td>
        <td><%= link_to item.title, item %></td>
        <td><%= item.description %></td>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

src/unit15/barter/app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

src/unit15/barter/app/views/items/show.html.erb
<p>
	<%= image_tag(@item.image.to_s, class: 'list_image') %> 
</p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<% if @item.belongs_to_me? %>
	<%= link_to 'Edit', edit_item_path(@item) %>
  <%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
	<% if @item.status == "Avaliable" %>
		<%= link_to 'Make Offer', new_offer_path(:item_id => @item.id) %>
	<% end %>
<% end %>